---
version: "3.7"
services:
  ts-sidecar:
    image: tailscale/tailscale:latest
    hostname: ts-sidecar-nats-cli-socks
    environment:
      - TS_AUTHKEY #=tskey-auth-kV7bYL6CNTRL-GXXhAHWhHXAVTcumJyyxXAc2cyjxQ3QkD
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SOCKS5_SERVER=:1055 # Set SOCKS5 proxy to listen on port 1055
      - TS_TAILSCALED_EXTRA_ARGS=--tun=userspace-networking # Use userspace networking
    volumes:
      - ${PWD}/data/ts-sidecar/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    # removed cap_add because using SOCKS5 proxy
    # cap_add:
    #   - net_admin
    #   - sys_module
    restart: unless-stopped
  nats-publisher:
    image: alpine:latest
    restart: unless-stopped
    network_mode: service:ts-sidecar
    command: >
      /bin/sh -c '
      apk add --no-cache curl util-linux &&
      curl -sfL https://binaries.nats.dev/nats-io/natscli/nats@latest | sh &&
      uuidgen > ./uniqueuuid &&
      while true; do
        ./nats pub ts.broadcast "Hello from NATS cli (socks) with UUID $(cat ./uniqueuuid)" --server=nats://100.69.178.62:4222 --socks-proxy=socks5://localhost:1055;
        sleep 1;
      done'
